// <auto-generated />
namespace MvcMusicStore_V5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MvcMusicStore_V5ModelsMusicContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MvcMusicStore_V5ModelsMusicContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201609091818500_MvcMusicStore_V5.Models.MusicContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
